// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtupswhhnizvavxgheet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0dXBzd2hobml6dmF2eGdoZWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTI4OTMsImV4cCI6MjA2MzkyODg5M30.V6J7xD8cAdltXwBCIUYy9HRZdG5dNEq7Bwbgb8k5_hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);